export const EDIT_BUDGET = 'EDIT_BUDGET';
export const EDIT_BALANCE = 'EDIT_BALANCE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CURRENT_USER_EXPENSES = 'CURRENT_USER_EXPENSES';
export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';
